const flightsData = {
  flights: {
    AB123: {
      flightNumber: "AB123",
      airline: "Delta Airlines",
      departureCity: "New York",
      departureAirport: "JFK",
      arrivalCity: "Los Angeles",
      arrivalAirport: "LAX",
      departureDate: "2023-09-01",
      arrivalDate: "2023-09-01",
      departureTime: "09:00",
      arrivalTime: "12:00",
      flightDuration: 180,
      price: 250.0,
    },
    AB1223: {
      flightNumber: "AB1223",
      airline: "Delta Airlines",
      departureCity: "Los Angeles",
      departureAirport: "LAX",
      arrivalCity: "New York",
      arrivalAirport: "JFK",
      departureDate: "2023-09-02",
      arrivalDate: "2023-09-02",
      departureTime: "09:00",
      arrivalTime: "12:00",
      flightDuration: 180,
      price: 250.0,
    },
    AB123223: {
      flightNumber: "AB123223",
      airline: "Delta Airlines",
      departureCity: "Los Angeles",
      departureAirport: "JFK",
      arrivalCity: "New York",
      arrivalAirport: "LAX",
      departureDate: "2023-09-02",
      arrivalDate: "2023-09-02",
      departureTime: "10:00 ",
      arrivalTime: "15:00",
      flightDuration: 300,
      price: 300.0,
    },
    AB123sd223: {
      flightNumber: "AB123sd223",
      airline: "Delta Airlines",
      departureCity: "Los Angeles",
      departureAirport: "JFK",
      arrivalCity: "New York",
      arrivalAirport: "LAX",
      departureDate: "2023-09-01",
      arrivalDate: "2023-09-01",
      departureTime: "11:00",
      arrivalTime: "14:00",
      flightDuration: 180,
      price: 300.0,
    },
    CD456: {
      flightNumber: "CD456",
      airline: "American Airlines",
      departureCity: "Los Angeles",
      departureAirport: "LAX",
      arrivalCity: "San Francisco",
      arrivalAirport: "SFO",
      departureDate: "2023-09-02",
      arrivalDate: "2023-09-02",
      departureTime: "14:30",
      arrivalTime: "15:45",
      flightDuration: 75,
      price: 150.5,
    },
    EF789: {
      flightNumber: "EF789",
      airline: "United Airlines",
      departureCity: "Miami",
      departureAirport: "MIA",
      arrivalCity: "Las Vegas",
      arrivalAirport: "LAS",
      departureDate: "2023-09-03",
      arrivalDate: "2023-09-03",
      departureTime: "11:00",
      arrivalTime: "14:30",
      flightDuration: 210,
      price: 300.0,
    },
    GH012: {
      flightNumber: "GH012",
      airline: "JetBlue Airways",
      departureCity: "Las Vegas",
      departureAirport: "LAS",
      arrivalCity: "New York",
      arrivalAirport: "JFK",
      departureDate: "2023-09-04",
      arrivalDate: "2023-09-04",
      departureTime: "15:45",
      arrivalTime: "20:00",
      flightDuration: 255,
      price: 350.75,
    },
    IJ345: {
      flightNumber: "IJ345",
      airline: "United Airlines",
      departureCity: "New York",
      departureAirport: "JFK",
      arrivalCity: "San Francisco",
      arrivalAirport: "SFO",
      departureDate: "2023-09-05",
      arrivalDate: "2023-09-05",
      departureTime: "08:00",
      arrivalTime: "11:15",
      flightDuration: 195,
      price: 280.8,
    },
    KL678: {
      flightNumber: "KL678",
      airline: "American Airlines",
      departureCity: "San Francisco",
      departureAirport: "SFO",
      arrivalCity: "Chicago",
      arrivalAirport: "ORD",
      departureDate: "2023-09-06",
      arrivalDate: "2023-09-06",
      departureTime: "13:45",
      arrivalTime: "16:30",
      flightDuration: 165,
      price: 220.6,
    },
    MN901: {
      flightNumber: "MN901",
      airline: "Delta Airlines",
      departureCity: "Chicago",
      departureAirport: "ORD",
      arrivalCity: "Dallas",
      arrivalAirport: "DFW",
      departureDate: "2023-09-07",
      arrivalDate: "2023-09-07",
      departureTime: "09:30",
      arrivalTime: "11:45",
      flightDuration: 135,
      price: 180.9,
    },
    OP234: {
      flightNumber: "OP234",
      airline: "Southwest Airlines",
      departureCity: "Dallas",
      departureAirport: "DFW",
      arrivalCity: "Orlando",
      arrivalAirport: "MCO",
      departureDate: "2023-09-08",
      arrivalDate: "2023-09-08",
      departureTime: "12:15",
      arrivalTime: "15:00",
      flightDuration: 165,
      price: 210.5,
    },
    QR567: {
      flightNumber: "QR567",
      airline: "Qatar Airways",
      departureCity: "Orlando",
      departureAirport: "MCO",
      arrivalCity: "Las Vegas",
      arrivalAirport: "LAS",
      departureDate: "2023-09-09",
      arrivalDate: "2023-09-09",
      departureTime: "14:00",
      arrivalTime: "17:15",
      flightDuration: 195,
      price: 290.75,
    },
    ST890: {
      flightNumber: "ST890",
      airline: "American Airlines",
      departureCity: "Las Vegas",
      departureAirport: "LAS",
      arrivalCity: "Denver",
      arrivalAirport: "DEN",
      departureDate: "2023-09-10",
      arrivalDate: "2023-09-10",
      departureTime: "08:45",
      arrivalTime: "10:30",
      flightDuration: 105,
      price: 160.2,
    },
    UV123: {
      flightNumber: "UV123",
      airline: "United Airlines",
      departureCity: "Denver",
      departureAirport: "DEN",
      arrivalCity: "Seattle",
      arrivalAirport: "SEA",
      departureDate: "2023-09-11",
      arrivalDate: "2023-09-11",
      departureTime: "11:30",
      arrivalTime: "13:45",
      flightDuration: 135,
      price: 190.3,
    },
    WX456: {
      flightNumber: "WX456",
      airline: "Delta Airlines",
      departureCity: "Seattle",
      departureAirport: "SEA",
      arrivalCity: "Chicago",
      arrivalAirport: "ORD",
      departureDate: "2023-09-12",
      arrivalDate: "2023-09-12",
      departureTime: "15:30",
      arrivalTime: "20:00",
      flightDuration: 270,
      price: 320.0,
    },
    YZ789: {
      flightNumber: "YZ789",
      airline: "American Airlines",
      departureCity: "Chicago",
      departureAirport: "ORD",
      arrivalCity: "Atlanta",
      arrivalAirport: "ATL",
      departureDate: "2023-09-13",
      arrivalDate: "2023-09-13",
      departureTime: "09:15",
      arrivalTime: "12:00",
      flightDuration: 165,
      price: 220.6,
    },
    AA012: {
      flightNumber: "AA012",
      airline: "American Airlines",
      departureCity: "Atlanta",
      departureAirport: "ATL",
      arrivalCity: "Los Angeles",
      arrivalAirport: "LAX",
      departureDate: "2023-09-14",
      arrivalDate: "2023-09-14",
      departureTime: "13:30",
      arrivalTime: "15:45",
      flightDuration: 135,
      price: 290.8,
    },
    BB345: {
      flightNumber: "BB345",
      airline: "American Airlines",
      departureCity: "Los Angeles",
      departureAirport: "LAX",
      arrivalCity: "Dallas",
      arrivalAirport: "DFW",
      departureDate: "2023-09-15",
      arrivalDate: "2023-09-15",
      departureTime: "18:00",
      arrivalTime: "20:30",
      flightDuration: 150,
      price: 250.9,
    },
    CC678: {
      flightNumber: "CC678",
      airline: "Southwest Airlines",
      departureCity: "Dallas",
      departureAirport: "DFW",
      arrivalCity: "Orlando",
      arrivalAirport: "MCO",
      departureDate: "2023-09-16",
      arrivalDate: "2023-09-16",
      departureTime: "10:45",
      arrivalTime: "14:00",
      flightDuration: 195,
      price: 210.5,
    },
    DD901: {
      flightNumber: "DD901",
      airline: "Delta Airlines",
      departureCity: "Orlando",
      departureAirport: "MCO",
      arrivalCity: "Seattle",
      arrivalAirport: "SEA",
      departureDate: "2023-09-17",
      arrivalDate: "2023-09-17",
      departureTime: "15:15",
      arrivalTime: "18:30",
      flightDuration: 195,
      price: 290.75,
    },
    EE234: {
      flightNumber: "EE234",
      airline: "Delta Airlines",
      departureCity: "Seattle",
      departureAirport: "SEA",
      arrivalCity: "New York",
      arrivalAirport: "JFK",
      departureDate: "2023-09-18",
      arrivalDate: "2023-09-18",
      departureTime: "09:30",
      arrivalTime: "18:00",
      flightDuration: 510,
      price: 360.2,
    },
  },
};

export default flightsData;
